auto_reprovisioning_mode = "OnErrorOnly"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "{DPSSCOPE}"

[provisioning.attestation]
method = "symmetric_key"
registration_id = "{DEVICEID}"

symmetric_key = { value = "{SECRETKEY}" }

[edge_ca]
auto_generated_edge_ca_expiry_days = 3000

[aziot_keys]

[preloaded_keys]

[cert_issuance]

[preloaded_certs]

[agent]
name = "edgeAgent"
type = "docker"
imagePullPolicy = "on-create"

[agent.config]
image = "mcr.microsoft.com/azureiotedge-agent:1.2"

[agent.config.createOptions]

[agent.env]

[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
min_tls_version = "tls1.0"

[watchdog]
max_retries = "infinite"

[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"